### ISSUE TITLE
后台新建模块，前端调用的时候报错 ERROR 6068 Error: next() called multiple times

### ISSUE THREAD

**Issue by jasonwish** [cool-team-official/cool-admin-midway#11]
这是后台日志 说明接口成功调用
![image](https://user-images.githubusercontent.com/20253248/112927952-639f7700-9148-11eb-8ccf-a95955cf4a31.png)
这是后台报错 在日志记录之后
![image](https://user-images.githubusercontent.com/20253248/112927985-70bc6600-9148-11eb-9195-c26c1c5687c2.png)
这是后台代码
![image](https://user-images.githubusercontent.com/20253248/112928006-7a45ce00-9148-11eb-9719-8bf8d2a17047.png)
这是后台目录结构
![image](https://user-images.githubusercontent.com/20253248/112928056-8e89cb00-9148-11eb-8de2-6b2e1b4e4d77.png)
这是配置类详细
![image](https://user-images.githubusercontent.com/20253248/112928086-9b0e2380-9148-11eb-9f11-7e11a180118e.png)

**Comment by cool-team-official** [comment]
提供下模块的代码

**Comment by jasonwish** [comment]
抱歉刚刚在午休，模块的代码 你指的是？模块的配置文件马在最后一个图片有

**Comment by jasonwish** [comment]
模块的目录有截图 你是想看哪个目录下的？

**Comment by jasonwish** [comment]
重启后 错误在记录日志之前了
![image](https://user-images.githubusercontent.com/20253248/112940782-3b237700-9160-11eb-84ba-9c5b555a423a.png)

**Comment by cool-team-official** [comment]
就是发下你模块的代码

**Comment by jasonwish** [comment]
谢谢，刚刚我用排除法查到可能是entity代码的问题，我先调试一下然后做记录

**Comment by cool-team-official** [comment]
好的， 这一班不是框架的问题哈， 你看demo那个模块 也没啥特殊的

**Comment by jasonwish** [comment]
确实，只是这个报错有些看不懂，然后钻牛角尖一直以为是配置问题，谢谢。

**Comment by cool-team-official** [comment]
没事哈，有问题再发issue提问
