### ISSUE TITLE
所有以 `/app/` 开头的路径都是登录失效

### ISSUE THREAD

**Issue by ywzhaiqi** [cool-team-official/cool-admin-midway#111]
`src/modules/user/middleware/app.ts` 会导致所有以 `/app/` 开头的路径都是登录失效
```json
{"code":1001,"message":"登录失效~"}
```

应该改成这样吧？
```js
if (_.startsWith(url, '/app/user/')) {
```

**Comment by illuz** [comment]
+1 我也发现了这个问题，希望尽快解决，免得后人踩坑

**Comment by xinnix** [comment]
> `src/modules/user/middleware/app.ts` 会导致所有以 `/app/` 开头的路径都是登录失效
> 
> ```json
> {"code":1001,"message":"登录失效~"}
> ```
> 
> 应该改成这样吧？
> 
> ```js
> if (_.startsWith(url, '/app/user/')) {
> ```

你这应该是前端没拿到token或者发送请求没带token

**Comment by ywzhaiqi** [comment]
> > `src/modules/user/middleware/app.ts` 会导致所有以 `/app/` 开头的路径都是登录失效
> > ```json
> > {"code":1001,"message":"登录失效~"}
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > 应该改成这样吧？
> > ```js
> > if (_.startsWith(url, '/app/user/')) {
> > ```
> 
> 你这应该是前端没拿到token或者发送请求没带token

以 `/admin` 开头的才需要验证，以 /app/ 开头的不需要验证

**Comment by xinnix** [comment]
> 

这个中间件本身就是针对app路径鉴权的。如果你不想验证，在user/config里把这个全局中间件注释掉就行了

**Comment by ywzhaiqi** [comment]
> > 
> 
> 这个中间件本身就是针对app路径鉴权的。如果你不想验证，在user/config里把这个全局中间件注释掉就行了

`src/modules/base/middleware/authority.ts` 已经有鉴权。`user/middleware/app.ts` 让前面这个失效，前后冲突，造成了显而易见的疑惑。

**Comment by cool-team-official** [comment]
https://cool-js.com/admin/node/core/authority.html  这个文档有说明
