### ISSUE TITLE
连接pg数据库 执行init.sql 报错

### ISSUE THREAD

**Issue by The-planet** [cool-team-official/cool-admin-midway#114]
配置了pg数据库
<img width="457" alt="image" src="https://github.com/cool-team-official/cool-admin-midway/assets/38370716/ec3cb64d-524c-4eb1-baf9-fd906d4d15c4">
然后执行 `src/modules/base/init.sql`报错，pg的数据类型和mysql的列类型不一致
<img width="640" alt="image" src="https://github.com/cool-team-official/cool-admin-midway/assets/38370716/01cee5ce-b386-433d-8905-d99b38c60349">

建议提供一个pg版本的sql

**Comment by adleyang** [comment]
程序里面有些地方不支持pg，需要修改，也发现类似问题

**Comment by cool-team-official** [comment]
不支持pg
