### ISSUE TITLE
你们发布代码前都不测试的吗？

### ISSUE THREAD

**Issue by dayueba** [cool-team-official/cool-admin-midway#122]
`git clone https://github.com/cool-team-official/cool-admin-midway.git`

`npm run test` 

测试能跑通过不

**Comment by xinnix** [comment]
开源项目不能过分苛求。有问题修复了就pr

**Comment by dayueba** [comment]
问题解决了吗，怎么就关了。。

**Comment by fulus06** [comment]
> 问题解决了吗，怎么就关了。。

jestjs引起的上下文切换，所以测试用例无法使用。我最近还在找解决方案

**Comment by jackieZhouQQ** [comment]
> > 问题解决了吗，怎么就关了。。
> 
> jestjs引起的上下文切换，所以测试用例无法使用。我最近还在找解决方案

有解决方案了吗？

**Comment by fulus06** [comment]
> > > 问题解决了吗，怎么就关了。。
> > 
> > 
> > jestjs引起的上下文切换，所以测试用例无法使用。我最近还在找解决方案
> 
> 有解决方案了吗？

https://gitee.com/panda-foundation/panda-admin-midway 项目的`location-v8.ts`文件，原文我给忘记了。我好想在群里说过，很久之前了
