### ISSUE TITLE
如何调试 packages 下的自定义组件代码？

### ISSUE THREAD

**Issue by Kayakyx** [cool-team-official/cool-admin-midway#125]
你好， 如果要修改 packages 下的自定义组件的代码，是怎么进行开发调试的？每次修改完都要 重新 build，然后再在根项目里重新`npm install` 吗？

**Comment by cool-team-official** [comment]
对应的 packages  yarn build 然后会有一个dist目录     主项目 yarn add dist路径 即可

**Comment by Kayakyx** [comment]
谢谢你的回答！

后来我明白为什么会在 `packages` 的组件中的 src 下也放一个 `package.json` 了，这样就不用 `build`，可以直接主目录 `npm link ./packages/foo/src`, 对应的 `yarn` 命令应该是  ` yarn add link:./packages/foo/src`。

这样就通过符号链接将 `packages` 下的 `foo` 组件 链接到主项目里 `node_modules` 里了。每次修改 `packages `下 `foo` 组件的代码` node_modules` 里也会同步修改。
