### ISSUE TITLE
取消权限 路由标签不起作用还是401，另一种方式路由一直404

### ISSUE THREAD

**Issue by pangxiaolong** [cool-team-official/cool-admin-midway#127]
新建其他的文件夹比如：controller/open     建了src/modules/demo/controller/open/goods.ts，api路由应该怎么拼

**Comment by cool-team-official** [comment]
路径应该是   /open/demo/goods/xxx，xxx是你具体的方法，注意是post还是get

**Comment by pangxiaolong** [comment]
> 路径应该是/open/demo/goods/xxx，xxx是你具体的方法，注意是post还是get

404没错，我仅仅只是连接了数据库跑起来 然后在demo/controller下建了一个open文件夹，把app中的goods复制到了open下，访问http://127.0.0.1:8001/open/demo/goods/list。

[![pPnwt10.png](https://s1.ax1x.com/2023/08/11/pPnwt10.png)](https://imgse.com/i/pPnwt10)
[![pPnw5AH.png](https://s1.ax1x.com/2023/08/11/pPnw5AH.png)](https://imgse.com/i/pPnw5AH)
[![pPnwINd.png](https://s1.ax1x.com/2023/08/11/pPnwINd.png)](https://imgse.com/i/pPnwINd)

**Comment by pangxiaolong** [comment]
list竟然是post方法

**Comment by pangxiaolong** [comment]
@cool-team-official 文档中
// 这是6.x支持的，可以直接标记这个接口忽略token，更加灵活优雅，但是记得配合@CoolUrlTag()一起使用，也就是Controller上要有这个注解，@CoolTag才会生效
@CoolTag(TagTypes.IGNORE_TOKEN)

为什么CoolTag没有引入方式，@cool-midway/core也没有导出

**Comment by cool-team-official** [comment]
你需要更新下 @cool-midway/core 这个包到最新
