### ISSUE TITLE
重写crud,调用super.page(param); keyWordLikeFields: ['out_trade_no'],模糊查询就没效果了

### ISSUE THREAD

**Issue by caolonggang** [cool-team-official/cool-admin-midway#134]
需求是把用户的手机号隐藏中间四位，所以重写crud,
重写方法如下：
  async page(param: any) {
    const data = await super.page(param);
    data.list.forEach(item => {
      if (item.mobile) {
        item.mobile = item.mobile.replace(/(\d{3})(\d{4})(\d{4})/, '$1****$3');
      }
    });
    return data;
  }
  
  这时候配置的模糊查询就没效果了
  @CoolController({
  api: ['add', 'delete', 'update', 'info', 'list', 'page'],
  entity: OrderEntity,
  service: OrderService,
  pageQueryOp: {
    addOrderBy: {
      create_time: 'desc',
    },
    keyWordLikeFields: ['out_trade_no'],
  }
})

**Comment by cool-team-official** [comment]
最后执行的sql 打印出来看下

**Comment by cool-team-official** [comment]
未能复现您说的情况
