### ISSUE TITLE
文件上传，云存储能增加minio吗？

### ISSUE THREAD

**Issue by shoppinglink** [cool-team-official/cool-admin-midway#146]
文件上传，云存储能增加minio吗？

**Comment by cool-team-official** [comment]
minio 是兼容aws s3的  你可以用s3这个插件

**Comment by shoppinglink** [comment]
我之前有试过aws，不过在哪里配置可以把上传方式改成这种模式 {http://endpoint/bucketname}

**Comment by shoppinglink** [comment]
> minio 是兼容aws s3的 你可以用s3这个插件

我之前有试过aws，不过不知道在哪里配置可以把上传方式改成这种模式 {[http://endpoint/bucketname}](http://endpoint/bucketname%7D)

**Comment by jackieZhouQQ** [comment]
![image](https://github.com/cool-team-official/cool-admin-midway/assets/108133430/35719861-cc35-4d49-ab98-cc176a8e6ac1)
最新的cool-file改过了，支持域名加/，不用s3的二级域名，指定forcePathStyle: true

**Comment by shoppinglink** [comment]
新版本可以了，谢谢
