### ISSUE TITLE
在文件管理中上传视频，服务端报错

### ISSUE THREAD

**Issue by GentleSevenV** [cool-team-official/cool-admin-midway#157]
在文件管理中上传视频，服务端报错。。。
![PixPin_2023-12-30_16-37-51](https://github.com/cool-team-official/cool-admin-midway/assets/48819497/069f8ab3-b707-4d71-bccf-12d5883239b6)
![PixPin_2023-12-30_16-39-22](https://github.com/cool-team-official/cool-admin-midway/assets/48819497/8493ac03-e0c1-4043-98a5-84295f256bc0)

**Comment by GentleSevenV** [comment]
上传模式为本地上传

**Comment by cool-team-official** [comment]
[本地静态文件改为流式传输](https://github.com/cool-team-official/cool-admin-midway/commit/9a66469241575a33837c31a9c4061f7f84a135d0)

**Comment by GentleSevenV** [comment]
好的，问题已解决，另外在此感谢一下官方大佬：神仙都没用
