### ISSUE TITLE
v7的本地开发遇到的关于swagger问题

### ISSUE THREAD

**Issue by xiaozhu188** [cool-team-official/cool-admin-midway#158]
1. execute无法输入参数；
![QQ20240107-170646](https://github.com/cool-team-official/cool-admin-midway/assets/20502995/b9e87004-faa6-4bc4-b485-db53aa6a7108)

2. authorize之后，请求头没有带上token；
3. 修改configuration.ts，添加swagger启动报错了。
import * as swagger from '@midwayjs/swagger';
imports: [
  swagger
]

**Comment by amys1013** [comment]
我也遇到这个问题了，请问后面怎么解决的啊？
