### ISSUE TITLE
page接口报错 SelectQueryBuilder.addOrderBy "order" can accept only "ASC" and "DESC" values.

### ISSUE THREAD

**Issue by Alioth1017** [cool-team-official/cool-admin-midway#19]
midwayjs-cool-core\service\base.js
方法：getOptionFind
// 接口请求的排序处
```
for (const i in sorts) {
    find.addOrderBy(orders[i], sorts[i]);
}
```
此处的sorts特定情况下会被污染读取到原型链上的属性导致接口报错
需修改成如下
`sorts.forEach((_,i)=>find.addOrderBy(orders[i], sorts[i]))`

**Comment by cool-team-official** [comment]
报错很明显了， 排序方式错误sorts[i]需要是“ASC”或者“DESC”

**Comment by Alioth1017** [comment]
传入的是DESC 但是因为原型链被污染导致原型连上的属性也加入到了排序中 导致报错

**Comment by Alioth1017** [comment]
参数信息如下：
node版本：v14.16.0
![微信图片编辑_20210418222935](https://user-images.githubusercontent.com/10696356/115149202-9d9fd100-a095-11eb-845e-aa01cef393ee.jpg)
第一次取值正确：
![微信图片编辑_20210418222946](https://user-images.githubusercontent.com/10696356/115149206-a0022b00-a095-11eb-9c9e-702bdf98b6b7.jpg)
第二次开始取原型链上的属性：
![微信图片编辑_20210418222953](https://user-images.githubusercontent.com/10696356/115149209-a1cbee80-a095-11eb-9dda-d47366b145c4.jpg)

**Comment by cool-team-official** [comment]
代码是怎么写的呢

**Comment by Alioth1017** [comment]
用的框架自动生成的page接口
/admin/base/sys/param/page
