### ISSUE TITLE
自动添加 00：00：00

### ISSUE THREAD

**Issue by XJain01** [cool-team-official/cool-admin-midway#20]
![image](https://user-images.githubusercontent.com/80761980/115143761-cb781c00-a07b-11eb-901e-a8a248a0f37e.png)
![image](https://user-images.githubusercontent.com/80761980/115143768-d5018400-a07b-11eb-96bb-c920784034dd.png)
自动添加 00：00：00的问题怎么解决

**Comment by cool-team-official** [comment]
建议阅读下typeorm.io官网文档
