### ISSUE TITLE
midwayjs-cool-core不开源吗

### ISSUE THREAD

**Issue by SunTYu** [cool-team-official/cool-admin-midway#3]

**Comment by cool-team-official** [comment]
开源的

**Comment by SunTYu** [comment]
没找到仓库地址。。。

**Comment by Gitsifu** [comment]
midwayjs-cool-core的文档好像也没有，请问什么时候能出文档呢？

**Comment by SunTYu** [comment]
大佬发个仓库地址学习学习

**Comment by cjl255352** [comment]
大佬可以发下仓库地址吗？最好别的官方插件也发一下，想学习下咋写插件

**Comment by cjl255352** [comment]
> 开源的

大佬🤣  求插件源码，咚咚咚！！🙏

**Comment by youtiao66** [comment]
+1 我也想知道 midwayjs-cool-core 的源码在哪里？

**Comment by youtiao66** [comment]
> 开源的

+1 求翻牌，想知道源码在哪里。

**Comment by Mikasa33** [comment]
> > 开源的
> 
> +1 求翻牌，想知道源码在哪里。

这不是开源的，要花钱买才行

**Comment by LaPoPvLe** [comment]
https://github.com/cool-team-official/cool-admin-midway-packages
