### ISSUE TITLE
midwayjs-cool-core初始化，处理模块config中middlewares存在换行(\n)时报错

### ISSUE THREAD

**Issue by amorwilliams** [cool-team-official/cool-admin-midway#32]
midwayjs-cool-core [v3.2.17] 核心库在初始化时，配置config模块中的公用中间件（middlewares）数组，当数组存在换行时 并没有考虑到换行符\n的处理，导致JSON解析错误。希望能修复一下，感谢。
![image](https://user-images.githubusercontent.com/1756137/123559248-6e13f000-d7cd-11eb-96a4-fc5153f400e3.png)
![image](https://user-images.githubusercontent.com/1756137/123559452-acf67580-d7ce-11eb-8c30-2e8469a054fe.png)

**Comment by cool-team-official** [comment]
已修复
