### ISSUE TITLE
内存泄漏

### ISSUE THREAD

**Issue by amorwilliams** [cool-team-official/cool-admin-midway#33]
运行时发现node内存不释放，dev和prod环境都存在问题，怀疑存在内存泄漏。
之前群里好像也有人提过这问题，本地开发的时候也是内存一直涨，直到oom。
然后进过排查。
 1. 发现直接跑midway初始工程，正常。
 2. 所以排除node版本和系统的问题。
 3. 将cool工程中，configuration只保留cool核心库，去除插件，内存依旧不释放。
 4. 删除所有module只保留welcome.ts，内存依旧不释放。
 5. 将welcome控制器改为midway的Controller，恢复正常。
 6. 加上redis插件，内存又不释放了。

泄漏截图 （第4步的状态）
![image](https://user-images.githubusercontent.com/1756137/125148434-c0a5c280-e164-11eb-838b-7907a3ea4456.png)

替换CoolController使用midway默认Controller的截图（第5步状态）
![image](https://user-images.githubusercontent.com/1756137/125161254-d55d7700-e1b3-11eb-8150-48f6e095b5f0.png)

下图是通过alinode拉取的堆快照，控制器没有释放掉。
![image](https://user-images.githubusercontent.com/1756137/125148894-129c1780-e168-11eb-9328-b4e23f4be339.png)

**Comment by amorwilliams** [comment]
补充一下：
我看到cool使 用了[func-loc](https://github.com/midrissi/func-loc) 这个库
由于controller作用于是Request的 每次请求进来midway会创建新的controller，而使用了@CoolController之后每次都会通过func-loc去查找路径
![image](https://user-images.githubusercontent.com/1756137/125161547-86184600-e1b5-11eb-93f7-229a5533dd01.png)

在fun-loc文档中有这么一句
![image](https://user-images.githubusercontent.com/1756137/125161605-dbecee00-e1b5-11eb-93b3-2a832670a111.png)

猜测可能创建的controller被fun-loc挂在到了global上，所以没有被gc回收。

**Comment by cythb** [comment]
看上去这个项目无法用在生产环境
