### ISSUE TITLE
今天来买你们程序了 结果发现被拉黑了？这么没肚量么？

### ISSUE THREAD

**Issue by huoyoo** [cool-team-official/cool-admin-midway#34]
今天来买你们程序了 结果发现被拉黑了？这么没肚量么？
我真是服了。
![微信截图_20210721190330](https://user-images.githubusercontent.com/74869290/126478819-4002fc7e-a9f9-4ae5-a87d-3c96d333525b.png)

**Comment by cythb** [comment]
马上这个也没了。哈哈

**Comment by huoyoo** [comment]
> 马上就没有了。哈哈

太惨了~
