### ISSUE TITLE
配置多数据库链接后 crud的page和list没有设置connectionName

### ISSUE THREAD

**Issue by amorwilliams** [cool-team-official/cool-admin-midway#37]
![image](https://user-images.githubusercontent.com/1756137/128313351-256b4e9f-ce07-4190-9416-ad3e5d3a12b7.png)

**Comment by cool-team-official** [comment]
多数据库是设置在实体类  不是在查询的时候选

**Comment by amorwilliams** [comment]
自己的业务是可以通过实体类注入（@InjectEntityModel）的时候指定connectionName
而cool框架内的curd，因为是动态生成的，是通过链接池查询的，不存在实体类注入。

**Comment by yaoli789** [comment]
我设置在实体类还是提示 No repository for "xxxEntity" was found. Looks like this entity is not registered in current "default" connection?
