### ISSUE TITLE
定时任务出现内存泄露问题

### ISSUE THREAD

**Issue by zengjinhui** [cool-team-official/cool-admin-midway#40]
重现步骤：
1.拉取最新代码无论是midwayjs版还是egg版
2.直接容器运行
3.新建10个空任务（打印日志都可以）几秒一跑
4.内存就会一直往上并且不会停，一晚上几百MB往上，一周不管直接破GB级别

**Comment by amorwilliams** [comment]
midwayjs-cool-core核心库中有使用到func-loc库， 可能存在内存泄露的问题。我之前也碰到过，一天不到内存直接OOM，你可以查查看，不知道是不是同样的问题。
