### ISSUE TITLE
多数据库支持报 *Entity找不到

### ISSUE THREAD

**Issue by loveeazy** [cool-team-official/cool-admin-midway#45]
触发例子如下：
1.config 配置多数据库

>  config.orm = {

    default: {
      type: 'mysql',
      host: '127.0.0.1',
      port: 3306,
      username: 'midway',
      password: '123123',
      database: 'cooladmin',
      synchronize: true,
      logging: true,
      charset: 'utf8mb4',
    },
    test1: {
      type: 'mysql',
      host: '127.0.0.1',
      port: 3306,
      username: 'root',
      password: '12345678',
      database: 'dashboard',
      synchronize: true,
      logging: true,
      charset: 'utf8mb4',

    },
  };

2.修改内部 demo/entity/goods.ts 及 demo/service/goods.ts

> `@EntityModel('demo_app_goods',{
  connectionName: 'test1'
})`

> `@Provide()
export class DemoGoodsService extends BaseService {
  @InjectEntityModel(DemoAppGoodsEntity,'test1')
  demoAppGoodsEntity: Repository<DemoAppGoodsEntity>;`

服务重启后，即报错
**RepositoryNotFoundError: No repository for "DemoAppGoodsEntity" was found. Looks like this entity is not registered in current "default" connection?**

观察到数据库表被成功更新
![image](https://user-images.githubusercontent.com/25704923/136785647-3a546a94-aa2a-4391-b4e4-9e9e5e80b783.png)

期待修复

**Comment by cool-team-official** [comment]
需要再Controller也指定连接名
`@CoolController(
  {
    api: ['add', 'delete', 'update', 'info', 'list', 'page'],
    entity: { entityKey: DemoAppGoods1Entity, connectionName: 'test' },
    listQueryOp: {
      keyWordLikeFields: ['title'],
    },
  },
  {
    middleware: [],
  }
)`
