### ISSUE TITLE
项目启动不知道道什么原因一直报错 

### ISSUE THREAD

**Issue by q975702873** [cool-team-official/cool-admin-midway#46]
项目启动不一会就一直报错
![image](https://user-images.githubusercontent.com/45583296/138225181-d5881b38-590b-4c42-b6ec-6e679bfb0c26.png)

![image](https://user-images.githubusercontent.com/45583296/138225036-5ecb174c-4c31-4824-af93-76ee5d021815.png)

数据库配置
![image](https://user-images.githubusercontent.com/45583296/138225308-466d31da-6115-4cd2-ac0a-89a37760ec9d.png)
![image](https://user-images.githubusercontent.com/45583296/138225367-c9c4932c-0deb-4e42-aea3-0fff33175118.png)

**Comment by cool-team-official** [comment]
拉取最新项目试试

**Comment by cool-team-official** [comment]
数据库版本 要求大于等于 5.7
