### ISSUE TITLE
不支持mysql8.0

### ISSUE THREAD

**Issue by carlisliu** [cool-team-official/cool-admin-midway#5]
mysql客户端8.0+
提示：ER_NOT_SUPPORTED_AUTH_MODE，

ER_NOT_SUPPORTED_AUTH_MODE: Client does not support authentication protocol requested by server; consider upgrading MySQL client

mysql数据库已经执行了：
ALTER USER 'root'@'localhost' IDENTIFIED WITH mysql_native_password BY 'password';
还是报错， 框架内部进行了相关处理吗？

**Comment by cool-team-official** [comment]
支持的，这个不是框架问题， https://blog.csdn.net/u013697959/article/details/99176376

**Comment by carlisliu** [comment]
> 支持的，这个不是框架问题， https://blog.csdn.net/u013697959/article/details/99176376

**Comment by carlisliu** [comment]
> 支持的，这个不是框架问题， https://blog.csdn.net/u013697959/article/details/99176376

试过，还是不行，不知道是不是sequelize处理的问题，pending一下，等有时间向下再查查
