### ISSUE TITLE
task无法执行

### ISSUE THREAD

**Issue by weiyunpeng** [cool-team-official/cool-admin-midway#75]
报TypeError: Cannot read properties of undefined (reading 'getRepeatableJobs')

**Comment by he1q** [comment]
开启队列

**Comment by weiyunpeng** [comment]
> 开启队列

确实....midway自带的task和cool的task是两个，默认还没开启。

**Comment by yaoli789** [comment]
TypeError: Cannot read property 'getRepeatableJobs' of undefined  
 我看代码本地任务是默认开启的。但还是提示这个

**Comment by Nodewebzsz** [comment]
请问这个开启任务是在哪里设置的呢，求告知
