### ISSUE TITLE
七牛文件上传有bug

### ISSUE THREAD

**Issue by zhisenyang** [cool-team-official/cool-admin-midway#87]

**Comment by zhisenyang** [comment]
bug地方：

![0dfbbfeeade60e2f5033a68871cacc6](https://user-images.githubusercontent.com/3937526/184913815-9c21b764-7576-4100-8289-0010edd86d55.jpg)

浅浅的修复一下，非严谨，没判断region。

![d7f6ed6560b328c2733e44e32310c73](https://user-images.githubusercontent.com/3937526/184913970-0dab499a-522c-4504-b70a-80aa0ce064a4.jpg)

**Comment by cool-team-official** [comment]
已修复

**Comment by cool-team-official** [comment]
https://github.com/cool-team-official/cool-admin-midway/commit/f8e7978f78d28d929a4313f18f6b7ed08aa0ccc5
