### ISSUE TITLE
build之后 /admin/base/open/eps 为什么不返回内容呢

### ISSUE THREAD

**Issue by wzs28150** [cool-team-official/cool-admin-midway#88]
为什么我后端build 之后 执行start后 前台访问时这个接口什么都不返回呢
![image](https://user-images.githubusercontent.com/21290257/186442376-c79683dc-f4e1-438c-b20f-06fc9394b8fe.png)
dev的时候就有内容
![image](https://user-images.githubusercontent.com/21290257/186442553-a2c82c0a-8db9-4331-a01f-76340c012fca.png)

**Comment by cool-team-official** [comment]
是的，eps是开发的时候使用的，生产环境安全考虑不应返回这些信息

**Comment by sponing** [comment]
那怎么处理这个问题呢，自定义的接口，前端页面都获取不到了
<img width="896" alt="image" src="https://github.com/cool-team-official/cool-admin-midway/assets/81665401/1153182b-0549-480b-8605-7c7fff3a55b4">

**Comment by cool-team-official** [comment]
连接开发环境 打包
