### ISSUE TITLE
启动后自动新建了表，但是没有导入数据

### ISSUE THREAD

**Issue by kof1290** [cool-team-official/cool-admin-midway#93]
![1666064232936](https://user-images.githubusercontent.com/16951027/196329783-b6dbd71a-c2fa-4650-ac62-c1a6b071fd5e.png)

![1666064149904](https://user-images.githubusercontent.com/16951027/196329630-1da84605-fa35-4e81-beec-af96c5ffc947.png)
![1666064165187](https://user-images.githubusercontent.com/16951027/196329724-2d5ae291-8145-4883-bd1b-6070e6c22b8c.png)

**Comment by cool-team-official** [comment]
删除lock文件夹再试
