### ISSUE TITLE
Unknown column 'asc' in 'order clause'" 生成sql有误

### ISSUE THREAD

**Issue by Jioho** [cool-team-official/cool-admin-midway#98]
使用 cool-admin-vue 5.x 和 cool-admin-midway 5.x 默认模版排序字段报错。提示 Unknown column 'asc' in 'order clause'"

**Comment by Jioho** [comment]
mysql 版本是 5.7.26

**Comment by Jioho** [comment]
![image](https://user-images.githubusercontent.com/28078590/210161323-42b2ce34-eddb-4bc2-aebe-2f6afeea34f2.png)

**Comment by tangchi695** [comment]
我也遇到了，这是前端代码的问题，@cool-vue/crud 这个包发了新版本的升级包，但是新版本有bug。你把前端依赖的这个包锁5.7.1版本安装就好了。

开发部署的时候最好都锁版本，前端和后端都把yarn.lock 和package-lock.json文件放到仓库锁定依赖。不然自动装新的包有坑。

另外这个包升级到6.0.3了，依然没有修复这个bug。。。

**Comment by cool-team-official** [comment]
版本6 还没发布

**Comment by icssoa** [comment]
> 我也遇到了，这是前端代码的问题，@cool-vue/crud 这个包发了新版本的升级包，但是新版本有bug。你把前端依赖的这个包锁5.7.1版本安装就好了。
> 
> 开发部署的时候最好都锁版本，前端和后端都把yarn.lock 和package-lock.json文件放到仓库锁定依赖。不然自动装新的包有坑。
> 
> 另外这个包升级到6.0.3了，依然没有修复这个bug。。。

改了格式，前端crud模块那边
<img width="828" alt="image" src="https://user-images.githubusercontent.com/23646980/212043978-429b0fd9-8ded-4e10-85d9-88f2f721e5d3.png">

**Comment by tangchi695** [comment]
> > 我也遇到了，这是前端代码的问题，@cool-vue/crud 这个包发了新版本的升级包，但是新版本有bug。你把前端依赖的这个包锁5.7.1版本安装就好了。
> > 开发部署的时候最好都锁版本，前端和后端都把yarn.lock 和package-lock.json文件放到仓库锁定依赖。不然自动装新的包有坑。
> > 另外这个包升级到6.0.3了，依然没有修复这个bug。。。
> 
> 改了格式，前端crud模块那边 <img alt="image" width="828" src="https://user-images.githubusercontent.com/23646980/212043978-429b0fd9-8ded-4e10-85d9-88f2f721e5d3.png">

这个配置没有生效，我在群里反馈过了

**Comment by icssoa** [comment]
> 

仔细对比
