### ISSUE TITLE
七牛云上传问题

### ISSUE THREAD

**Issue by xiatianshitiancai** [cool-team-official/cool-admin-midway#99]
async qiniu(ctx) {
        const { bucket, publicDomain, region } = this.config.qiniu;
        let options = {
            scope: bucket,
        };
        const putPolicy = new QINIU.rs.PutPolicy(options);
        const uploadToken = putPolicy.uploadToken(this.client);
        return new Promise((resolve, reject) => {
            resolve({
               // 此处的upload 需要动态替换成up
                uploadUrl: `https://**upload**-${region}.qiniup.com/`,
                publicDomain,
                token: uploadToken,
                fileKey: 'file',
            });
        });
    }

**Comment by cool-team-official** [comment]
更新包（支持外部配置）： 

- @cool-midway/file  5.1.2  
- @cool-midway/core  5.1.8
